const flakes = require('simpleflakes')

/**
 * Default error and message for when an unavailable choice is attempted to be voted on and
 * `anyInput = false`.
 *
 * @returns {Error}
 */
const unavailableChoice = new Error('This value is not in the available choices, and anyInput is set to false.')

/**
 * A basic poll object that allows for easier tracking of surveys and polls.
 *
 * @class
 * @prop {string} label A string that indicates the label/question to display.
 * @prop {string} startTime A string that indicates when the poll should start.
 * @prop {string} endTime A string that indicates when the poll should end.
 * @prop {string[]} values An optional string array of acceptable answers.
 * @prop {boolean} anyInput An optional boolean that indicates if values that have not been previously defined can be used.
 * @prop {string} id The optional unique string id for this given poll, if none is provided, it is generated using `simpleflakes`.
 */
class Poll {
  /**
   *
   * @param {object} options
   * @param {string} options.label The label/descrption to display for the poll.
   * @param {string} options.startTime When the poll should start.
   * @param {string} options.endTime When the poll should end.
   * @param {string[]} [options.values] An array of acceptable answers to the poll.
   * @param {boolean} [options.anyInput] Whether or not any
   * @param {string} [id] The unique id for this given poll, randomly generated by default.
   */
  constructor (options, id) {
    // Set required parameters
    this.label = options.label
    this.startTime = options.startTime
    this.endTime = options.endTime

    // Set optional parameters
    if (options.values === undefined) this.values = new Map()
    else options.values.forEach(val => { this.values[val] = 0 })

    if (options.allowMultiple === undefined) this.allowMultiple = false
    else this.allowMultiple = options.allowMultiple

    if (options.anyInput === undefined) this.anyInput = false
    else this.anyInput = options.anyInput

    if (id === undefined) {
      this.id = flakes.simpleflake(Date.now(), 23).toString()
    } else this.id = id
  }

  /**
   * If any input is allowed, the given choice is incremented by 1 or set to 1 if it
   * is the first time to be voted on. If not, then the given choice has its vote
   * count increased and resulting value returned.
   *
   * @param {string} choice
   * @returns {Promise<number>}
   */
  vote (choice) {
    return new Promise((resolve, reject) => {
      if (this.anyInput) {
        let currVal = this.values.get(choice)

        if (currVal === undefined) {
          this.values.set(choice, 1)
        } else {
          this.values.set(choice, currVal + 1)
        }

        resolve(this.values.get(choice))
      } else {
        let currVal = this.values.get(choice)

        if (currVal === undefined) reject(unavailableChoice)
        else {
          this.values.set(choice, currVal + 1)
          resolve(this.values.get(choice))
        }
      }
    })
  }
}

module.exports = Poll
